# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          cd ..
          sudo apt-get install ninja-build nasm mtools genisoimage
          wget https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/latest
          unzip latest
          cd Night
      - name: Build
        run: |
          ./../gn gen out
          ninja -C out
      - name: Get GRUB Image
        run: |
          wget http://littleosbook.github.com/files/stage2_eltorito
          mv stage2_eltorito iso/boot/grub/stage2_eltorito
      - name: Make Iso
        run: |
          mkdir -p iso/boot/grub
          touch iso/boot/grub/grub.cfg
          mv out/kernel iso/boot/krnl
          genisoimage -R                              \
                -b boot/grub/stage2_eltorito    \
                -no-emul-boot                   \
                -boot-load-size 4               \
                -A os                           \
                -input-charset utf8             \
                -quiet                          \
                -boot-info-table                \
                -o Night.iso                       \
                iso
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          name: Night.iso
          # A file, directory or wildcard pattern that describes what to upload
          path: Night.iso
